name: "github-actions-releaser"
description: "Release GitHub actions versions"
branding:
  color: "green"
  icon: "book-open"
inputs:
  PROJECT_NAME:
    description: "The name of the project to be released"
    required: true
  GITHUB_TOKEN:
    description: "The file that the output report will be written to"
    required: true
  RELEASE_BRANCH:
    description: "The branch to release from"
    required: true
    default: "main"
runs:
  using: "composite"
  steps:
  # Checkout repo
  - name: Checkout
    uses: actions/checkout@v4
  - name: Write release config
    shell: bash
    env:
      PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
      RELEASE_BRANCH: ${{ inputs.RELEASE_BRANCH }}
    run: |
      # Create temporary release directory
      mkdir "${GITHUB_SHA}"
      
      # Copy the package.json file from the action to the current directory
      cp ${{ github.action_path}}/docs/package.json "${GITHUB_SHA}"/package.json
      
      # Update the package.json file with the project name
      sed -i "s/PROJECT_NAME/${PROJECT_NAME}/g" "${GITHUB_SHA}"/package.json
      
      echo -e '{
        "name": "'${PROJECT_NAME}'",
        "branches": ["'${RELEASE_BRANCH}'"]
      }' >> "${GITHUB_SHA}"/.releaserc

  - name: Setup Node.js
    uses: actions/setup-node@v4
    with:
      node-version: 'lts/*'
  - name: Install dependencies
    shell: bash
    run: |
      cd "${GITHUB_SHA}"
      npm install

  - name: Release
    shell: bash
    env:
      GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    run: |
      cd "${GITHUB_SHA}"
      npx semantic-release
